In [9]:
import numpy as np
import pandas as pd
import seaborn as sns

In [10]:
# ==== Columns to Keep (reference list)====
"""
filtered_columns = {
    "STATEQ": "State",
    "CENSUSDIV": "Census Division",
    "CENSUSREG": "Census Region",
    "A50A": "Gender",
    "A3Ar_w": "Age Group",
    "A50B": "Gender&Age",
    "A5_2015": "Education",
    "A8_2021": "Annual Income",
    "B1": "Checking Account",
    "B2": "Savings Account",
    "B4": "Overdraw",  
    "B14A_1": "Other Investments",    
    "C5_2012": "Other Retirement Accounts",
    "F1": "Number of Credit Cards",
    "F2_2": "Credit Card Balance Interest",
    "J5": "Emergency Funds",
    "J8": "Retirement Planning",
    "H1": "Health Insurance"
    "M1_1": "Financial Confidence",
    "M4": "Financial Knowledge"
}
"""

'\nfiltered_columns = {\n    "STATEQ": "State",\n    "CENSUSDIV": "Census Division",\n    "CENSUSREG": "Census Region",\n    "A50A": "Gender",\n    "A3Ar_w": "Age Group",\n    "A50B": "Gender&Age",\n    "A5_2015": "Education",\n    "A8_2021": "Annual Income",\n    "B1": "Checking Account",\n    "B2": "Savings Account",\n    "B4": "Overdraw",  \n    "B14A_1": "Other Investments",    \n    "C5_2012": "Other Retirement Accounts",\n    "F1": "Number of Credit Cards",\n    "F2_2": "Credit Card Balance Interest",\n    "J5": "Emergency Funds",\n    "J8": "Retirement Planning",\n    "H1": "Health Insurance"\n    "M1_1": "Financial Confidence",\n    "M4": "Financial Knowledge"\n}\n'

In [11]:
# ========= Work on 2024 dataset =========

# Set relative path to the dataset on GitHub
df2024_path = 'https://raw.githubusercontent.com/Fasty8/ba780-fall25-a08/refs/heads/cleaning/FINRA%20National%20Financial%20Capability%20Study/2024-SxS-Data-and-Data-Info/NFCS%202024%20State%20Data%20250623.csv'

# Load 2024 dataset and replace missing values with NaN
df2024 = pd.read_csv(df2024_path, na_values=["", " ", "NA", "N/A", "null", ".", "na"])

# Filter df2024 to keep only the selected columns and stored in a new DataFrame 'filtered_df2024'
filtered_df2024 = df2024[[
                        'STATEQ', 'CENSUSDIV', 'CENSUSREG' ,'A50A', 'A3Ar_w', 'A50B', 'A5_2015', 'A8_2021', 'B1', 
                        'B2', 'B4', 'B14A_1', 'C5_2012', 'F1', 'F2_2', 'J5', 'J8', 'H1', 'M1_1', 'M4'
                        ]]

In [12]:
# ======================== Create dictionary list to map values in each column =========================

# STATEQ (2) State
state = {
    1: "Alabama", 2: "Alaska", 3: "Arizona", 4: "Arkansas", 5: "California",
    6: "Colorado", 7: "Connecticut", 8: "Delaware", 9: "District of Columbia",
    10: "Florida", 11: "Georgia", 12: "Hawaii", 13: "Idaho", 14: "Illinois",
    15: "Indiana", 16: "Iowa", 17: "Kansas", 18: "Kentucky", 19: "Louisiana",
    20: "Maine", 21: "Maryland", 22: "Massachusetts", 23: "Michigan",
    24: "Minnesota", 25: "Mississippi", 26: "Missouri", 27: "Montana",
    28: "Nebraska", 29: "Nevada", 30: "New Hampshire", 31: "New Jersey",
    32: "New Mexico", 33: "New York", 34: "North Carolina", 35: "North Dakota",
    36: "Ohio", 37: "Oklahoma", 38: "Oregon", 39: "Pennsylvania", 40: "Rhode Island",
    41: "South Carolina", 42: "South Dakota", 43: "Tennessee", 44: "Texas",
    45: "Utah", 46: "Vermont", 47: "Virginia", 48: "Washington", 49: "West Virginia",
    50: "Wisconsin", 51: "Wyoming"
}

# CENSUSDIV (3) Census Division
census_div = {
    1: "New England",
    2: "Middle Atlantic",
    3: "East North Central",
    4: "West North Central",
    5: "South Atlantic",
    6: "East South Central",
    7: "West South Central",
    8: "Mountain",
    9: "Pacific"
}

# CENSUSREG (4) Census Region
census_reg = {
    1: "Northeast",
    2: "Midwest",
    3: "South",
    4: "West"
}

# A50A (5) Gender (nonbinary randomly assigned)
gender = {
    1: "Male",
    2: "Female"
}

# A3Ar_w (6) Age group
age_group = {
    1: "18-24",
    2: "25-34",
    3: "35-44",
    4: "45-54",
    5: "55-64",
    6: "65+"
}

# A50B (7) Gender/Age net (nonbinary randomly assigned)
gender_age = {
    1: "Male 18-24",
    2: "Male 25-34",
    3: "Male 35-44",
    4: "Male 45-54",
    5: "Male 55-64",
    6: "Male 65+",
    7: "Female 18-24",
    8: "Female 25-34",
    9: "Female 35-44",
    10: "Female 45-54",
    11: "Female 55-64",
    12: "Female 65+"
}

# A5_2015 (9) Highest education completed
education = {
    1: "Did not complete high school",
    2: "High school graduate - regular high school diploma",
    3: "High school graduate - GED or alternative credential",
    4: "Some college, no degree",
    5: "Associate's degree",
    6: "Bachelor's degree",
    7: "Post graduate degree",
    99: "Prefer not to say"
}

# A8_2021 (14) Household approximate annual income
annual_income = {
    1: "Less than $15,000",
    2: "At least $15,000 but less than $25,000",
    3: "At least $25,000 but less than $35,000",
    4: "At least $35,000 but less than $50,000",
    5: "At least $50,000 but less than $75,000",
    6: "At least $75,000 but less than $100,000",
    7: "At least $100,000 but less than $150,000",
    8: "At least $150,000 but less than $200,000",
    9: "At least $200,000 but less than $300,000",
    10: "$300,000 or more",
    98: "Don't know",
    99: "Prefer not to say"
}

# B1 (60) Do you [Does your household] have a checking account?
checking_account = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# B2 (61) Do you [Does your household] have a savings account, money market account, or CDs?
savings_account = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# B4 (62) Do you [or your spouse/partner] overdraw your checking account occasionally?
overdraw = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# B14A_1 (77) Not including retirement accounts, do you [does your household] have any investments in... - Stocks, bonds, mutual funds, or other securities
other_investments = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# C5_2012 (74) Do you [or your spouse/partner] regularly contribute to a retirement account like a [Thrift Savings Plan (TSP),] 401(k) or IRA?
other_retirement_accounts = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# F1 (88) Number of credit cards
num_credit_cards = {
    1: "1",
    2: "2 to 3",
    3: "4 to 8",
    4: "9 to 12",
    5: "13 to 20",
    6: "More than 20",
    7: "No credit cards",
    98: "Don't know",
    99: "Prefer not to say"
}

# F2_2 (98) In the past 12 months, which of the following describes your experience with credit cards? - IN SOME MONTHS, I CARRIED OVER A BALANCE AND WAS CHARGED INTEREST.
credit_card_balance_interest = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# J5 (30) Emergency or rainy day funds
emergency_funds = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# J8 (27) Have you ever tried to figure out how much you need to save for retirement?
retirement_planning = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# H1 (104) Are you covered by health insurance?
health_insurance = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# M1_1 (117) How strongly do you agree or disagree with the following statement? - I am good at dealing with day-to-day financial matters, such as checking accounts, credit and debit cards, and tracking expenses
financial_confidence = {
    1: "Strongerly disagree",
    2: "Moderately disagree",
    3: "Slightly disagree",
    4: "Neither agree nor disagree",
    5: "Slightly agree",
    6: "Moderately agree",
    7: "Strongly agree",
    98: "Don't know",
    99: "Prefer not to say"
}

# M4 (118) Self-assessed financial knowledge (1-7)
financial_knowledge = {
    1: "1", # very low
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7", # very high
    98: "Don't know",
    99: "Prefer not to say"
}

In [13]:
# ======== RENAME AND REPLACE ========

# ============= Re-name columns to more readable names =============
column_names_mapping = {
    "STATEQ": "State",
    "CENSUSDIV": "Census Division",
    "CENSUSREG": "Census Region",
    "A50A": "Gender",
    "A3Ar_w": "Age Group",
    "A50B": "Gender&Age",
    "A5_2015": "Education",   
    "A8_2021": "Annual Income",
    "B1": "Checking Account",
    "B2": "Savings Account",
    "B4": "Overdraw",     
    "B14A_1": "Other Investments",
    "C5_2012": "Other Retirement Accounts",   
    "F1": "Number of Credit Cards",
    "F2_2": "Credit Card Balance Interest",
    "J5": "Emergency Funds",  
    "J8": "Retirement Planning",
    "H1": "Health Insurance",
    "M1_1": "Financial Confidence",
    "M4": "Financial Knowledge",
}

# ================ Match column names to coded values dicts ================
column_values_mapping = {
    "State": state,
    "Census Division": census_div,
    "Census Region": census_reg,
    "Gender": gender,
    "Age Group": age_group,
    "Gender&Age": gender_age,
    "Education": education,
    "Annual Income": annual_income,
    "Checking Account": checking_account,
    "Savings Account": savings_account,
    "Overdraw": overdraw,
    "Other Investments": other_investments,
    "Other Retirement Accounts": other_retirement_accounts,
    "Number of Credit Cards": num_credit_cards,
    "Credit Card Balance Interest": credit_card_balance_interest,
    "Emergency Funds": emergency_funds,
    "Retirement Planning": retirement_planning,
    "Health Insurance": health_insurance,
    "Financial Confidence": financial_confidence,
    "Financial Knowledge": financial_knowledge
}

# ========= Replace values and Rename columns. Saved to a new df 'cleaned_df2024' ===========
cleaned_df2024 = filtered_df2024.rename(columns=column_names_mapping)

In [14]:
cleaned_df2024.head()

,State,Census Division,Census Region,Gender,Age Group,Gender&Age,Education,Annual Income,Checking Account,Savings Account,Overdraw,Other Investments,Other Retirement Accounts,Number of Credit Cards,Credit Card Balance Interest,Emergency Funds,Retirement Planning,Health Insurance,Financial Confidence,Financial Knowledge
0,36,3,2,2,3,9,6,8,1,1,2.0,1.0,1.0,2,1.0,1,1.0,1,5,6
1,48,9,4,1,6,6,5,5,1,1,2.0,2.0,2.0,3,2.0,1,NaN,1,7,6
2,38,9,4,1,6,6,4,7,1,1,2.0,2.0,NaN,3,1.0,1,NaN,1,7,7
3,48,9,4,2,6,12,7,5,1,1,2.0,1.0,2.0,1,1.0,1,1.0,1,6,5
4,44,7,3,2,6,12,7,4,1,1,1.0,1.0,1.0,2,1.0,2,NaN,1,7,6

## FinLit Calculation

In [15]:
# ======================================
# BUCKET 1: Critical Stability (max 5 each)
# ======================================
emergency_funds_w = {  # J5 — Emergency or rainy day funds
    1: 5,  # Yes
    2: 1,  # No
    98: 0, 99: 0, "No Response Given": 0
}

retirement_planning_w = {  # J8 — Tried to figure out retirement savings
    1: 5,
    2: 1,
    98: 0, 99: 0, "No Response Given": 0
}

health_insurance_w = {  # H1 — Covered by health insurance
    1: 5,
    2: 1,
    98: 0, 99: 0, "No Response Given": 0
}

# ======================================
# BUCKET 2: Core Access & Assets (max 3 each)
# ======================================
checking_account_w = {  # B1
    1: 3,
    2: 1,
    98: 0, 99: 0, "No Response Given": 0
}

savings_account_w = {  # B2
    1: 3,
    2: 1,
    98: 0, 99: 0, "No Response Given": 0
}

other_investments_w = {  # B14 — Non-retirement investments
    1: 3,
    2: 1,
    98: 0, 99: 0, "No Response Given": 0
}

retirement_planning_w = {  # C5 — Contribute to retirement account
    1: 3,
    2: 1,
    98: 0, 99: 0, "No Response Given": 0
}

# ======================================
# BUCKET 3: Credit Health & Debt Behavior (max 3 each)
# ======================================
overdraw_w = {  # B4 — Overdraw checking?
    2: 3,  # No (best)
    1: 1,  # Yes
    98: 0, 99: 0, "No Response Given": 0
}

credit_card_balance_interest_w = {  # F2_2 — Carried balance & charged interest
    2: 3,  # No (best)
    1: 1,  # Yes
    98: 0, 99: 0, "No Response Given": 0
}

num_credit_cards_w = {  # F1 — Number of credit cards
    2: 3,  # 2–3 (ideal)
    3: 3,  # 4–8
    1: 2,  # 1
    4: 1,  # 9–12
    5: 0,  # 13–20
    6: 0,  # >20
    7: 1,  # None
    98: 0, 99: 0, "No Response Given": 0
}


# ======================================
# COMBINED WEIGHTS DICTIONARY
# ======================================
WEIGHTS = {
    # Bucket 1: Critical Stability
    "Emergency Funds": emergency_funds_w,
    "Retirement Planning": retirement_planning_w,
    "Health Insurance": health_insurance_w,

    # Bucket 2: Core Access & Assets
    "Checking Account": checking_account_w,
    "Savings Account": savings_account_w,
    "Other Investments": other_investments_w,
    "Other Retirement Accounts": retirement_planning_w,

    # Bucket 3: Credit Health & Debt Behavior
    "Overdraw": overdraw_w,
    "Credit Card Balance Interest": credit_card_balance_interest_w,
    "Number of Credit Cards": num_credit_cards_w,
}

# GRAND TOTAL MAX = 15 + 12 + 9 + 10 = 46

for col, weight_dict in WEIGHTS.items():
    # financial_literacy[f"{col}_score"] = financial_literacy[col].map(weight_dict)
    cleaned_df2024[f"{col}_score"] = cleaned_df2024[col].map(weight_dict)

In [16]:
cleaned_df2024 = cleaned_df2024.replace(column_values_mapping)

In [17]:
cleaned_df2024["Total_Score"] = cleaned_df2024[[f"{col}_score" for col in WEIGHTS.keys()]].sum(axis=1)

conditions = [
    (cleaned_df2024["Total_Score"] >= 40),                                      # Very High
    (cleaned_df2024["Total_Score"] >= 34) & (cleaned_df2024["Total_Score"] < 40),  # High
    (cleaned_df2024["Total_Score"] >= 27) & (cleaned_df2024["Total_Score"] < 34),  # Moderately High
    (cleaned_df2024["Total_Score"] >= 20) & (cleaned_df2024["Total_Score"] < 27),  # Average
    (cleaned_df2024["Total_Score"] >= 13) & (cleaned_df2024["Total_Score"] < 20),  # Moderately Low
    (cleaned_df2024["Total_Score"] >= 6)  & (cleaned_df2024["Total_Score"] < 13),  # Low
    (cleaned_df2024["Total_Score"] >= 0)  & (cleaned_df2024["Total_Score"] < 6),    # Very Low
    (cleaned_df2024["Total_Score"] == 0)                             # No Response Given
]

choices = [
    "Very High", 
    "High", 
    "Moderately High", 
    "Average", 
    "Moderately Low", 
    "Low", 
    "Very Low", 
    "None"
]

cleaned_df2024["FinLit_Level"] = np.select(conditions, choices, default="No Response Given")

In [18]:
# Total missing values in each column
cleaned_df2024.isna().sum().sort_values(ascending=False)

cleaned_df2024.to_csv("Cleaned 2024.csv", index=False)

In [19]:
# NEXT STEPS

"""
1. Mimic the same cleaning and mapping process in 2012 and 2009 datasets
2. Merge all three cleaned datasets
3. Create two new columns 'total_score' and 'finlit_level' <------ This one I'm not sure if we should calculate
                                                                    them in each dataset first before the merge.
4. Once above are complete, we have a finalized dataset ready for analyses!
"""

"\n1. Mimic the same cleaning and mapping process in 2012 and 2009 datasets\n2. Merge all three cleaned datasets\n3. Create two new columns 'total_score' and 'finlit_level' <------ This one I'm not sure if we should calculate\n                                                                    them in each dataset first before the merge.\n4. Once above are complete, we have a finalized dataset ready for analyses!\n"