In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
# ==== Columns to Keep (reference list)====
"""
filtered_columns = {
    "A3Ar_w": "Age Group",
    "A8_2021": "Annual Income",
    "CENSUSDIV": "Census Division",
    "CENSUSREG": "Census Region",
    "B1": "Checking Account",
    "J8": "Retirement Planning",
    "F1": "Credit Card",
    "F2_2": "Credit Card Balance Interest",
    "A5_2015": "Education",
    "J5": "Emergency Funds",
    "M1_1": "Financial Confidence",
    "M4": "Financial Knowledge",
    "A50A": "Gender",
    "A50B": "Gender&Age",
    "B14A_1": "Other Investments",
    "C5_2012": "Other Retirement Accounts",
    "B4": "Overdraw",
    "B2": "Savings Account",
    "STATEQ": "STATEQ",
    "H1": "Health Insurance",
    "M20": "Financial Education"
}
"""

'\nfiltered_columns = {\n    "A3Ar_w": "Age Group",\n    "A8_2021": "Annual Income",\n    "CENSUSDIV": "Census Division",\n    "CENSUSREG": "Census Region",\n    "B1": "Checking Account",\n    "J8": "Retirement Planning",\n    "F1": "Credit Card",\n    "F2_2": "Credit Card Balance Interest",\n    "A5_2015": "Education",\n    "J5": "Emergency Funds",\n    "M1_1": "Financial Confidence",\n    "M4": "Financial Knowledge",\n    "A50A": "Gender",\n    "A50B": "Gender&Age",\n    "B14A_1": "Other Investments",\n    "C5_2012": "Other Retirement Accounts",\n    "B4": "Overdraw",\n    "B2": "Savings Account",\n    "STATEQ": "STATEQ",\n    "H1": "Health Insurance",\n    "M20": "Financial Education"\n}\n'

In [2]:
# ========= Work on 2024 dataset =========

# Set relative path to the dataset on GitHub
df2024_path = 'https://raw.githubusercontent.com/Fasty8/ba780-fall25-a08/refs/heads/cleaning/FINRA%20National%20Financial%20Capability%20Study/2024-SxS-Data-and-Data-Info/NFCS%202024%20State%20Data%20250623.csv'

# Load 2024 dataset and replace missing values with NaN
df2024 = pd.read_csv(df2024_path, na_values=["", " ", "NA", "N/A", "null", ".", "na"])

# Filter df2024 to keep only the selected columns and stored in a new DataFrame 'filtered_df2024'
filtered_df2024 = df2024[[
                        'A3Ar_w', 'A8_2021', 'CENSUSDIV', 'CENSUSREG', 'B1', 'J8', 'F1', 'F2_2',
                        'A5_2015', 'J5', 'M1_1', 'M4', 'A50A', 'A50B',
                        'B14A_1', 'C5_2012', 'B4', 'B2',
                        'STATEQ', 'H1', 'M20'
                        ]]

In [3]:
# ======================== Create dictionary list to map values in each column =========================

# A3Ar_w (6) Age group
age_group = {
    1: "18-24",
    2: "25-34",
    3: "35-44",
    4: "45-54",
    5: "55-64",
    6: "65+"
}

# A8_2021 (14) Household approximate annual income
annual_income = {
    1: "Less than $15,000",
    2: "At least $15,000 but less than $25,000",
    3: "At least $25,000 but less than $35,000",
    4: "At least $35,000 but less than $50,000",
    5: "At least $50,000 but less than $75,000",
    6: "At least $75,000 but less than $100,000",
    7: "At least $100,000 but less than $150,000",
    8: "At least $150,000 but less than $200,000",
    9: "At least $200,000 but less than $300,000",
    10: "$300,000 or more",
    98: "Don't know",
    99: "Prefer not to say"
}

# CENSUSDIV (3) Census Division
census_div = {
    1: "New England",
    2: "Middle Atlantic",
    3: "East North Central",
    4: "West North Central",
    5: "South Atlantic",
    6: "East South Central",
    7: "West South Central",
    8: "Mountain",
    9: "Pacific"
}

# CENSUSREG (4) Census Region
census_reg = {
    1: "Northeast",
    2: "Midwest",
    3: "South",
    4: "West"
}

# B1 (60) Do you [Does your household] have a checking account?
checking_account = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# J8 (27) Have you ever tried to figure out how much you need to save for retirement?
retirement_planning = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# F1 (88) Number of credit cards
num_credit_cards = {
    1: "1",
    2: "2 to 3",
    3: "4 to 8",
    4: "9 to 12",
    5: "13 to 20",
    6: "More than 20",
    7: "No credit cards",
    98: "Don't know",
    99: "Prefer not to say"
}

# F2_2 (98) In the past 12 months, which of the following describes your experience with credit cards? - IN SOME MONTHS, I CARRIED OVER A BALANCE AND WAS CHARGED INTEREST.
credit_card_balance_interest = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# A5_2015 (9) Highest education completed
education = {
    1: "Did not complete high school",
    2: "High school graduate - regular high school diploma",
    3: "High school graduate - GED or alternative credential",
    4: "Some college, no degree",
    5: "Associate's degree",
    6: "Bachelor's degree",
    7: "Post graduate degree",
    99: "Prefer not to say"
}

# J5 (30) Emergency or rainy day funds
emergency_funds = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# M1_1 (117) How strongly do you agree or disagree with the following statement? - I am good at dealing with day-to-day financial matters, such as checking accounts, credit and debit cards, and tracking expenses
financial_confidence = {
    1: "Strongerly disagree",
    2: "Moderately disagree",
    3: "Slightly disagree",
    4: "Neither agree nor disagree",
    5: "Slightly agree",
    6: "Moderately agree",
    7: "Strongly agree",
    98: "Don't know",
    99: "Prefer not to say"
}

# M4 (118) Self-assessed financial knowledge (1-7)
financial_knowledge = {
    1: "1", # very low
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7", # very high
    98: "Don't know",
    99: "Prefer not to say"
}

# A50A (5) Gender (nonbinary randomly assigned)
gender = {
    1: "Male",
    2: "Female"
}

# A50B (7) Gender/Age net (nonbinary randomly assigned)
gender_age = {
    1: "Male 18-24",
    2: "Male 25-34",
    3: "Male 35-44",
    4: "Male 45-54",
    5: "Male 55-64",
    6: "Male 65+",
    7: "Female 18-24",
    8: "Female 25-34",
    9: "Female 35-44",
    10: "Female 45-54",
    11: "Female 55-64",
    12: "Female 65+"
}

# B14A_1 (77) Not including retirement accounts, do you [does your household] have any investments in... - Stocks, bonds, mutual funds, or other securities
other_investments = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# C5_2012 (74) Do you [or your spouse/partner] regularly contribute to a retirement account like a [Thrift Savings Plan (TSP),] 401(k) or IRA?
other_retirement_accounts = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# B4 (62) Do you [or your spouse/partner] overdraw your checking account occasionally?
overdraw = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# B2 (61) Do you [Does your household] have a savings account, money market account, or CDs?
savings_account = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# STATEQ (2) State
stateq = {
    1: "Alabama", 2: "Alaska", 3: "Arizona", 4: "Arkansas", 5: "California",
    6: "Colorado", 7: "Connecticut", 8: "Delaware", 9: "District of Columbia",
    10: "Florida", 11: "Georgia", 12: "Hawaii", 13: "Idaho", 14: "Illinois",
    15: "Indiana", 16: "Iowa", 17: "Kansas", 18: "Kentucky", 19: "Louisiana",
    20: "Maine", 21: "Maryland", 22: "Massachusetts", 23: "Michigan",
    24: "Minnesota", 25: "Mississippi", 26: "Missouri", 27: "Montana",
    28: "Nebraska", 29: "Nevada", 30: "New Hampshire", 31: "New Jersey",
    32: "New Mexico", 33: "New York", 34: "North Carolina", 35: "North Dakota",
    36: "Ohio", 37: "Oklahoma", 38: "Oregon", 39: "Pennsylvania", 40: "Rhode Island",
    41: "South Carolina", 42: "South Dakota", 43: "Tennessee", 44: "Texas",
    45: "Utah", 46: "Vermont", 47: "Virginia", 48: "Washington", 49: "West Virginia",
    50: "Wisconsin", 51: "Wyoming"
}

# H1 (104) Are you covered by health insurance?
health_insurance = {
    1: "Yes",
    2: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

# M20 (119) Financial education offered at school/work
financial_education_offered = {
    1: "Yes, but I did not participate in the financial education offered",
    2: "Yes, and I did participate in the financial education",
    3: "No",
    98: "Don't know",
    99: "Prefer not to say"
}

In [5]:
# ======== RENAME AND REPLACE ========

# ============= Re-name columns to more readable names =============
column_names_mapping = {
    "A3Ar_w": "age_group",
    "A8_2021": "annual_income",
    "CENSUSDIV": "census_div",
    "CENSUSREG": "census_reg",
    "B1": "checking_account",
    "J8": "retirement_planning",
    "F1": "num_credit_cards",
    "F2_2": "credit_card_balance_interest",
    "A5_2015": "education",
    "J5": "emergency_funds",
    "M1_1": "financial_confidence",
    "M4": "financial_knowledge",
    "A50A": "gender",
    "A50B": "gender_age",
    "B14A_1": "other_investments",
    "C5_2012": "other_retirement_accounts",
    "B4": "overdraw",
    "B2": "savings_account",
    "STATEQ": "stateq",
    "H1": "health_insurance",
    "M20": "financial_education_offered"
}

# ================ Match column names to coded values dicts ================
column_values_mapping = {
    "A3Ar_w": age_group,
    "A8_2021": annual_income,
    "CENSUSDIV": census_div,
    "CENSUSREG": census_reg,
    "B1": checking_account,
    "J8": retirement_planning,
    "F1": num_credit_cards,
    "F2_2": credit_card_balance_interest,
    "A5_2015": education,
    "J5": emergency_funds,
    "M1_1": financial_confidence,
    "M4": financial_knowledge,
    "A50A": gender,
    "A50B": gender_age,
    "B14A_1": other_investments,
    "C5_2012": other_retirement_accounts,
    "B4": overdraw,
    "B2": savings_account,
    "STATEQ": stateq,
    "H1": health_insurance,
    "M20": financial_education_offered
    
}

# ========= Replace values and Rename columns. Saved to a new df 'cleaned_df2024' ===========
cleaned_df2024 = filtered_df2024.replace(column_values_mapping).rename(columns=column_names_mapping)

In [133]:
cleaned_df2024.head()

,age_group,annual_income,census_div,census_reg,checking_account,retirement_planning,num_credit_cards,credit_card_balance_interest,education,emergency_funds,...,financial_knowledge,gender,gender_age,other_investments,other_retirement_accounts,overdraw,savings_account,stateq,health_insurance,financial_education_offered
0,35-44,"At least $150,000 but less than $200,000",East North Central,Midwest,Yes,Yes,2 to 3,Yes,Bachelor's degree,Yes,...,6,Female,Female 35-44,Yes,Yes,No,Yes,Ohio,Yes,"Yes, and I did participate in the financial ed..."
1,65+,"At least $50,000 but less than $75,000",Pacific,West,Yes,NaN,4 to 8,No,Associate's degree,Yes,...,6,Male,Male 65+,No,No,No,Yes,Washington,Yes,"Yes, but I did not participate in the financia..."
2,65+,"At least $100,000 but less than $150,000",Pacific,West,Yes,NaN,4 to 8,Yes,"Some college, no degree",Yes,...,7,Male,Male 65+,No,NaN,No,Yes,Oregon,Yes,"Yes, and I did participate in the financial ed..."
3,65+,"At least $50,000 but less than $75,000",Pacific,West,Yes,Yes,1,Yes,Post graduate degree,Yes,...,5,Female,Female 65+,Yes,No,No,Yes,Washington,Yes,No
4,65+,"At least $35,000 but less than $50,000",West South Central,South,Yes,NaN,2 to 3,Yes,Post graduate degree,No,...,6,Female,Female 65+,Yes,Yes,Yes,Yes,Texas,Yes,No

In [7]:
# Total missing values in each column
cleaned_df2024.isna().sum().sort_values(ascending=False)

other_retirement_accounts       13731
retirement_planning              6144
credit_card_balance_interest     4968
overdraw                         1877
other_investments                1025
checking_account                    0
census_reg                          0
census_div                          0
annual_income                       0
age_group                           0
emergency_funds                     0
num_credit_cards                    0
education                           0
gender                              0
financial_knowledge                 0
financial_confidence                0
gender_age                          0
savings_account                     0
stateq                              0
health_insurance                    0
financial_education_offered         0
dtype: int64

In [ ]:
# NEXT STEPS

"""
1. Mimic the same cleaning and mapping process in 2012 and 2009 datasets
2. Merge all three cleaned datasets
3. Create two new columns 'total_score' and 'finlit_level' <------ This one I'm not sure if we should calculate
                                                                    them in each dataset first before the merge.
4. Once above are complete, we have a finalized dataset ready for analyses!
"""